CREATE TABLE IF NOT EXISTS "CLIENT"(
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" TEXT NOT NULL,
    "knowledge" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "ADDRESS"(
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "client_id" INTEGER,
    "name" TEXT NOT NULL,
    FOREIGN KEY (client_id) REFERENCES CLIENT (id) 
);